### ISSUE TITLE
Persistent store

### ISSUE THREAD

**Issue by flosse** [jaredonline/redux-rs#3]
How would you persist the store?
Let's say there are thousands of users and much more data objects. How would you handle this?

BTW: [Here](https://github.com/fanderzon/rust-redux/issues/2) is the same question ;-)

**Comment by jaredonline** [comment]
That would depend very much on the requirements of the system. In my mind, Redux states are meant to be maintained in memory, and written to disk when the process is exiting. So, for the game I'm making, I plan on having it "auto-save" every so-often, which will serialize the state and write it to disk. Then loading a game will just be deserializing that state into memory.

**Comment by flosse** [comment]
I see.. so you'd probably not recommend it for a "usual" application!?

**Comment by jaredonline** [comment]
Depends on how you define "usual" really. It's hard to give a recommendation without knowing more about the app, you know? I would checkout this post for reasons [not to use Redux](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367#.nr66f65rj) which all basically apply to this library as well [=

**Comment by jaredonline** [comment]
Gonna close but feel free to re-open if you have more questions [=
